# Site settings
title: "Jongho Jeon's Resume"
description: "Server Engineer with Kotlin/Spring, Kubernetes, and Docker container experience"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "전종호 (Jongho Jeon)"
resume_title:                   "Server Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hojong.jjh@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+8210-8808-5245"
resume_contact_address:         ""

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: |
  3년 차 서버 개발자입니다.<br>
  주로 Kotlin/Spring을 사용해 개발하고 있고, 필요에 따라 Python, TypeScript도 사용합니다.<br>
  Docker, Kubernetes 환경에서 2년 이상 서버를 개발, 배포 및 운영하고 있습니다.<br>
  호기심이 많으며, 리팩토링, 성능 최적화, 아키텍처 설계, 운영 자동화를 좋아합니다.<br>
  <p>
  Email: <a href="mailto:hojong.jjh@gmail.com">hojong.jjh@gmail.com</a>
  </p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/hojongs"
  # resume_twitter_url:           "http://twitter.com/hojong_j"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jh-jeon"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://hojongs.medium.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
